#!/bin/bash

# Check if directory is a valid directory
if ! [[ -d $1 ]]; then
  echo "Directory path is invalid!"
  exit 1
fi

# Extract folder name & exercise
folderName=$(basename $(pwd))
weekAndExercise=${folderName:8:6}
finalpath=$1/$weekAndExercise/test
if ! [[ -d $finalpath ]]; then
  echo "There seem to be no tests for $weekAndExercise available in $1"
  exit 1
fi

# Ignore changes on .gitignore and build file to stop them for being pushed to version control
git update-index --skip-worktree .gitignore
git update-index --skip-worktree build.gradle

# Push test folder into .gitignore
echo "/test" >> .gitignore

# Push test implementation into build.gradle file
if ! grep -F "org.junit.jupiter:junit-jupiter" build.gradle; then 
  echo -e "\ndependencies {\n    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'\n}" >> build.gradle
fi;

# Push useJUnitPlatform into build.gradle file
if ! grep -F "useJUnitPlatform()" build.gradle; then
  echo -e "\ntest {\n    useJUnitPlatform()\n}" >> build.gradle
fi;

# Replace test src dir in build.gradle file
perl -i -pe "s/srcDirs = [[]]/srcDirs = ['test']/" build.gradle

# Link test folder to repo
ln -s $finalpath
