#!/bin/bash

pathToTests="$1"

# Fallback to default path
if [ $# -eq 0 ]; then
    pathToTests="../pgdp2223-tests"
    echo "No test directory given, defaulted to $pathToTests"
fi

# Check if directory is a valid directory
if ! [[ -d "$pathToTests" ]]; then
  echo "Directory path is invalid!"
  exit 1
fi

# Extract folder name & exercise
folderName=$(basename $(pwd))
weekAndExercise=${folderName:8:6}
finalpath="$pathToTests/$weekAndExercise/test"
if ! [[ -d "$finalpath" ]]; then
  echo "There seem to be no tests for $weekAndExercise available in $pathToTests :("
  exit 1
fi

# Ignore changes on .gitignore and build file to stop them for being pushed to version control
git update-index --skip-worktree .gitignore
git update-index --skip-worktree build.gradle

# Push test folder into .gitignore
echo "/test" >> .gitignore

echo "Made git ignore the test files"

# Push test implementation into build.gradle file
if ! grep -qF "org.junit.jupiter:junit-jupiter" build.gradle; then 
  echo -e "\ndependencies {\n    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'\n}" >> build.gradle
  echo "Added junit to build.gradle"
fi;

# Push useJUnitPlatform into build.gradle file
if ! grep -qF "useJUnitPlatform()" build.gradle; then
  echo -e "\ntest {\n    useJUnitPlatform()\n}" >> build.gradle
  echo "Added useJUnitPlatform() to build.gradle"
fi;

# Replace test src dir in build.gradle file
perl -i -pe "s/srcDirs = [[]]/srcDirs = ['test']/" build.gradle

# Link test folder to repo
ln -s $finalpath
echo "Successfully linked tests"

echo "Happy testing!"
